channels:
  - conda-forge
  - default
dependencies:
  - einops
  - requests
  - pytest
  - click
  - joblib
  - tqdm
  - ipykernel
  - notebook
  - ipywidgets
  - jupyter
  - flask
  - matplotlib
  - numpy-stl
  - mediapy
  - pandas
  - scikit-learn
  - black
  - wandb==0.13.10
  - ftfy
  - tensorboard
  - pygame
  - plotly
  - sympy
  - accelerate
  - pre-commit
  - diffusers
  - gdown
  - jaxtyping
  - typeguard
  #- streamlit
  - torchinfo
  - frozendict
  #- streamlit-chat
  - pytorch-lightning
  - openai
  #- gym==0.23.1
  - pygame
  #- autorom[accept-rom-license]
  - ale-py
  - protobuf==3.20.3
  - mujoco
  #- free-mujoco-py
  - git
  - pip
  - pip:
    - git+https://github.com/callummcdougall/CircuitsVis.git#subdirectory=python
    - git+https://github.com/neelnanda-io/neel-plotly
    - transformer_lens